### PR TITLE
Bump task version

### PR DESCRIPTION
**Pull request by lgoudriaan**
The new changes are not visible in the pipelines, I think this is caused by the fact that the version number isn't automaticly updated. So I bumped the version + updated the readme. You can also bump the version automatically with: https://www.npmjs.com/package/azp-bump

### CODE REVIEW

**Comment by gioce90** [comment]
Hi, I see this in the settings of the Extension:

image
 
So is updated. 

But in my Release pipeline, I don't see the new option in the task:

image

Maybe something is missing?

**Comment by lgoudriaan** [comment]
I see, apparently the plugin is build and pushed via a github action which updates the task.json version from gitversion. And it looks like gitversion doesn't update it's version correctly so it's stuck at version 3.0.0. I haven't found the actual issue yet.

**Comment by gioce90** [comment]
maybe the problem is that?

image

The major I guess should be 3 or higher. An older major version maybe is not considered by ADO. I guess.

**Comment by BlueBasher** [comment]
The GitHub action overrides the versions specified in the task.json. SO version is purely based on git commits. Both for the Extension version and the Task version.
But there was a bug in the GitHub action that never updated the Patch of the Task version. Because that remained the same DevOps did not use a newer version. This has been fixed now in #128 
I just verified (rushed it yesterday because of vacation...rushing things is never good :) ) and it works perfectly! Thanks again for the contribution @lgoudriaan

**Pull request merged**
